DDD.WebUI/ViewModels/Product/ProductDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DDD.Domain.Entities;

namespace DDD.WebUI.ViewModels.Product
{
    public class ProductDetailViewModel : BaseProductCatalogPageViewModel
    {
        public ProductTitle Product { get; set; }
        public IEnumerable<ProductsQuantityViewModel> ProductsQuantityViewModels { get; set; }
        public int forCatalog { get; set; }
    }
}

DDD.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.WebUI.ViewModels.Admin;

namespace DDD.WebUI.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult GetCategoryCatalog()
        {
            return View("CategoryCatalog");
        }
        public ActionResult Index()
        {
            AdminMenu menu = new AdminMenu();
            return View(menu);
        }
      

    }
}

DDD.WebUI/Controllers/BrandAdminController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.Domain.Entities;
using DDD.Service.Admin;

namespace DDD.WebUI.Controllers
{
    public class BrandAdminController : Controller
    {
        private IAdminServices<Brand, int> adminServices;


        public BrandAdminController(IAdminServices<Brand, int> adminServices)
        {
            this.adminServices = adminServices;
        }

        public ActionResult Index()
        {

            return View(adminServices.GetAll());

        }

        public ViewResult Create()
        {
            return View("Edit", new Brand() { Id = 0 });
        }


        public ActionResult Edit(int Id)
        {
            return View(adminServices.GetBy(Id));
        }


        [HttpPost]
        public ActionResult Edit(Brand brand)
        {
            if (ModelState.IsValid)
            {
                if (brand.Id == 0) adminServices.Add(brand);
                else adminServices.Save(brand);
                return RedirectToAction("Index");
            }
            else
            {
                return View(brand);
            }
        }


        [HttpPost]
        public ActionResult Delete(int Id)
        {
            Brand brand = adminServices.GetBy(Id);
            if (brand != null)
            {

                adminServices.Remove(Id);
            }
            return RedirectToAction("Index");
        }


    }
}

DDD.WebUI/Controllers/CartController.cs
using DDD.Domain.Entities;
using DDD.Domain.Abstract;
using DDD.Domain.Basket;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.Repositories.Abstract;
using DDD.WebUI.ViewModels.Basket;
using DDD.WebUI.ModelBinder;
using DDD.Domain.Shipping;
using DDD.Domain.Order;
using DDD.Repositories.EF;

namespace DDD.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IRepositoryR<ProductTitle, int> repository;
        private IOrderProcessor orderProcessor;



        //--------------------------------------------------
        public CartController(IRepositoryR<ProductTitle, int> repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
       
        //----------------------------------------------------
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

       //------------------------------------------------------
        public ViewResult Index(Cart cart, string returnUrl)
        {


            return View(new CartIndexViewModel
            {

                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

      
        //----------------------------------------------
        public RedirectToRouteResult AddToCart(Cart cart, string returnUrl,
            int productId , int ProductColorId, int ProductSizeId,  int ProductQuantity)
        {

            ProductTitle product = repository.FindBy(productId);
            if (product != null)
            {

                cart.AddItem(product, ProductColorId,  ProductSizeId,  ProductQuantity);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        
       
        //-------------------------------------------------------------------
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AddToCartAjax(Cart cart,
           int ProductId, int ProductColorId, int ProductSizeId, int ProductQuantity)
        {
          
            ProductTitle product = repository.FindBy(ProductId);
            if (product != null)
            {              
                cart.AddItem(product, ProductColorId, ProductSizeId, ProductQuantity);
            }
            var newdata = new
            {
                CartQuantity = cart.TotalItems(),
                CartTotal = cart.ComputeTotalValue()
            };
            return Json(newdata, JsonRequestBehavior.AllowGet);
        }


        //--------------------------------------------
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            ProductTitle product = repository.FindBy(productId);
            if (product != null)
            {
               
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //---------------------------------------
        public ActionResult Checkout()
        {
            ShippingDetails details = new ShippingDetails();
            details.States = ((ProductTitleRepository)repository).GetProductStates();
            return View(details);
        }



        //-----------------------------------------
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

          
            if (shippingDetails.StateId == 0)
            {
                ModelState.AddModelError("StateId", "Please select a state");
                
            }

            if (ModelState.IsValid)
            {
                //orderProcessor.ProcessOrder(cart, shippingDetails);
                ((ProductTitleRepository)repository).ProcessOrder(cart.Lines);

                cart.Clear();
                return View("Completed");
            }
            else
            {

                    ShippingDetails details = new ShippingDetails();
                    shippingDetails.States = ((ProductTitleRepository)repository).GetProductStates();

                return View(shippingDetails);




            }
        }
    }
}

DDD.WebUI/Controllers/CategoryAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.Domain.Entities;
using DDD.Service.Admin;

namespace DDD.WebUI.Controllers
{
    public class CategoryAdminController : Controller
    {
        private IAdminServices<Category, int> adminServices;


        public CategoryAdminController(IAdminServices<Category, int> adminServices)
        {
            this.adminServices = adminServices;
        }  

       

        public ActionResult Index()
        {
            
            return View(adminServices.GetAll());
            
        }



        public ViewResult Create()
        {
            return View("Edit", new Category() { Id = 0 });
        }
  

        public ActionResult Edit(int Id)
        {
            return View(adminServices.GetBy(Id));
        }

       
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0) adminServices.Add(category);
                else adminServices.Save(category);
                         return RedirectToAction("Index");
            }
            else
            {
                return View(category);
            }
        }


        [HttpPost]
        public ActionResult Delete(int Id)
        {
            Category category = adminServices.GetBy(Id); 
            if (category != null)
            {
            
                 adminServices.Remove(Id);
            }
            return RedirectToAction("Index");
        }

        
    }
}

DDD.WebUI/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.Domain.Entities;
using DDD.Service.Admin;
using DDD.WebUI.ViewModels.Admin;
using DDD.Service.Model;
using System.IO;
using DDD.WebUI.Infrastructure.ValidationHelpers;
using DDD.Service.Product;



namespace DDD.WebUI.Controllers
{
    public class ProductAdminController : Controller
    {
        private IAdminServices<ProductTitle, int> adminServices;


        public ProductAdminController(IAdminServices<ProductTitle, int> adminServices)
        {
            this.adminServices = adminServices;
        }

        
        //--------------------------------------------------
        public ActionResult Index(int BrandId = 0, int CategoryId = 0,
           string OrderBy ="Id", int ItemsPerPage = 10, int CurrentPage = 1)
        {
            AllProductAttributeResponceModel attr = ((AdminProductServices)adminServices).GetAllProductAttributes(0);
            AdminHomePageViewModel adminHomePageViewModel = new AdminHomePageViewModel();


            adminHomePageViewModel.NumberOfResultsPerPage = ItemsPerPage;
            adminHomePageViewModel.Brands = attr.Brands.OrderBy(p => p.Name);
            adminHomePageViewModel.Categories = attr.Categories.OrderBy(p => p.Name);
            adminHomePageViewModel.Products = ((AdminProductServices)adminServices).GetAllBy(BrandId, CategoryId);
            adminHomePageViewModel.CurrentPage = CurrentPage;
            adminHomePageViewModel.AllItemsFound = adminHomePageViewModel.Products.Count();

            adminHomePageViewModel.OrderBy = OrderBy;
            var propertyInfo = typeof(ProductTitle).GetProperty(OrderBy);
            adminHomePageViewModel.Products=adminHomePageViewModel.
                      Products.OrderBy(p => propertyInfo.GetValue(p, null));

            adminHomePageViewModel.TotalPages = 
                       (int)Math.Ceiling((decimal)adminHomePageViewModel.AllItemsFound / ItemsPerPage);

            adminHomePageViewModel.Products = adminHomePageViewModel.Products                               
                               .Skip((CurrentPage -1) * ItemsPerPage).Take(ItemsPerPage);
                               
            return View(adminHomePageViewModel);

        }

        
        
        
        //-------------------------------------------------------------
        public ViewResult Create(string returnUrl)
        {
            AllProductAttributeResponceModel attr = ((AdminProductServices)adminServices).GetAllProductAttributes(0);

            ProductEditAdminViewModel productEditAdminViewModel = new ProductEditAdminViewModel();
            productEditAdminViewModel.ProductTitle = new ProductTitle()
            {
                Id = 0,
                Brand = new Brand() { Id = 0 },
                Category = new Category() { Id = 0 }
            };          
            productEditAdminViewModel.Brands = attr.Brands.OrderBy(p => p.Name);
            productEditAdminViewModel.Categories = attr.Categories.OrderBy(p => p.Name);
            productEditAdminViewModel.ReturnUrl = returnUrl;
         
            return View("Edit", productEditAdminViewModel);
        }

        
        //---------------------------------------------------------
        public ActionResult Edit(int id, string returnUrl)
        {
                     
            AllProductAttributeResponceModel attr = ((AdminProductServices)adminServices).GetAllProductAttributes(id);
            ProductEditAdminViewModel productEditAdminViewModel = new ProductEditAdminViewModel();

            productEditAdminViewModel.ProductTitle = adminServices.GetBy(id);
            productEditAdminViewModel.AddProductsQuantityToArray();                   
            productEditAdminViewModel.Brands = attr.Brands.OrderBy(p => p.Name);
            productEditAdminViewModel.Categories = attr.Categories.OrderBy(p => p.Name);
            productEditAdminViewModel.ReturnUrl = returnUrl;
            return View(productEditAdminViewModel);
        }

      
      
        //--------------------------------------------------------
        [HttpPost]
        public ActionResult Delete(int Id, string returnUrl)
        {
            ProductTitle productTitle = adminServices.GetBy(Id);            
            adminServices.Remove(Id);
            return Redirect(returnUrl);
        }



        //--------------------------------------------------
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult DeleteAjax (  int Id)
        {
            ProductTitle productTitle = adminServices.GetBy(Id);            
            adminServices.Remove(Id);            
            return Json(new { }, JsonRequestBehavior.AllowGet);
        }

        
      
        //--------------------------------------------------------------------------------
        [HttpPost]
        public ActionResult Edit(ProductTitle ProductTitle, IEnumerable<ProductQuantity> quantity,
                              string  returnUrl,
                              IEnumerable<HttpPostedFileBase> file, int[] fileId, int hasImages)
        {

            ModelState.CleanSometing("ProductTitle.Brand.Name", 
                        "ProductTitle.Brand.Description", "ProductTitle.Category.Name");
                          
            if (ProductTitle.Brand == null || ProductTitle.Brand.Id ==0)
            {               
                ModelState.AddModelError("ProductTitle.Brand.Id", "Please specify a  brand");
                ProductTitle.Brand.Id = 0;

            }
            if (ProductTitle.Category == null || ProductTitle.Category.Id == 0)
            {                
                ModelState.AddModelError("ProductTitle.Category.Id", "Please specify a category ");               
                ProductTitle.Category.Id = 0;
            }
           
     
            if (ModelState.IsValid)           
            {
                //Product Quantity Set
                ProductTitle.ProductsQuantity = ProductTitle.ProductsQuantity //quantity
                    .Where(p => p.Quantity > 0 || p.Id > 0)
                    .ToList();

                //Product Image Set
                if (hasImages == 1)
                {
                    var imageFiles = file.Select((image, i) => new
                    {

                        ImageOrderId = i + 1,
                        Image = image,
                        ProductTitleImage = (image == null ? null : new ProductTitleImage()
                        {
                            Name = "",
                            ImageOrderId = i + 1,
                            ImageMimeType = image.ContentType,
                            ImageData = new byte[image.ContentLength]
                        })
                    }).ToList();

                    foreach (var item in imageFiles)
                    {
                        if (item.Image != null)
                            item.Image.InputStream.Read(item.ProductTitleImage.ImageData, 0, item.Image.ContentLength);
                    }

                    var imageIds = fileId.Select((p, i) => new { ImageOrderId = i + 1, ImageId = p });

                    ProductTitle.ProductTitleImages = imageFiles
                                    .Join(imageIds,
                                     f => f.ImageOrderId,
                                     fId => fId.ImageOrderId,
                                     (f, fId) =>
                                         new ProductTitleImage()
                                         {
                                             Id = fId.ImageId,
                                             ImageOrderId = f.ImageOrderId,
                                             ImageData = (f.Image == null ? null : f.ProductTitleImage.ImageData),
                                             ImageMimeType = (f.Image == null ? "" : f.ProductTitleImage.ImageMimeType)
                                         }).ToList();
                }
                else
                {
                    ProductTitle.ProductTitleImages = null;
                }                 

                               
                adminServices.Save(ProductTitle);

                return Redirect(returnUrl);
            }
            else
            {
                ProductEditAdminViewModel productEditAdminViewModel = new ProductEditAdminViewModel();
                AllProductAttributeResponceModel attr =
                           ((AdminProductServices)adminServices).GetAllProductAttributes(ProductTitle.Id);
                productEditAdminViewModel.Brands = attr.Brands;
                productEditAdminViewModel.Categories = attr.Categories;               
                productEditAdminViewModel.ProductTitle = ProductTitle;
                productEditAdminViewModel.ReturnUrl = returnUrl;
                if (hasImages == 1 && fileId != null)
                {
                    productEditAdminViewModel.ProductTitle.ProductTitleImages = fileId
                        .Where(p => p > 0)
                        .Select(s => new ProductTitleImage() { Id = s })
                        .ToList();
                }
                 

                return View(productEditAdminViewModel);
            }
        }

    }
}

DDD.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-1.7.1.js" type="text/js"></script>
<script src="~/Scripts/jquery.validate.min.js" type="text/js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/js"></script>

<title></title>
</head>

<body>
    


<div id="header">

<div class="title">

    @RenderSection("TitleContent", required: false)
</div></div>

 <div id="divMenu">  
 @if (IsSectionDefined("MenuContent"))
 {
    @RenderSection("MenuContent", required: false)
}
else
  {
     @Html.ActionLink("Home", "Index", "Admin", null, new { id = "linkHomeAdmin" })
     @Html.ActionLink("Product", "Index", "ProductAdmin",null, new { id = "linkProductAdmin" })     
     @Html.ActionLink("Category", "Index", "CategoryAdmin",null, new { id = "linkCategoryAdmin" })
     @Html.ActionLink("Brand", "Index", "BrandAdmin",null, new { id = "linkBrandAdmin" })
     
     
  }

</div>

<div id="content">
    @RenderSection("MainContent", required: false)
</div>

@RenderBody()
  
</body>
</html>

DDD.WebUI/Views/Shared/_Cart.cshtml
@using DDD.Domain.Basket;
@model Cart

<div id="cart">
<span class="caption">
<b>Your cart:</b>
<span id="cartQuantity">@Model.Lines.Sum(x => x.Quantity)</span> item(s),
<span id="cartTotal">@Model.ComputeTotalValue().ToString("c")</span>
</span>
@Html.ActionLink("Checkout", "Index", "Cart", new
{
    returnUrl = Request.Url.PathAndQuery

}, new { id = "linkCart", onclick = "return checkCartQuantity();" })
</div>

<script type="text/javascript">
function checkCartQuantity()
{
   if ($("#cartQuantity").text() != "0") return true;
   else {
        alert( "Shopping cart is empty");
    return false;
   }
 }
 </script>

     

     

DDD.WebUI/Views/Shared/_Categories.cshtml
@using DDD.Domain.Entities;
@using DDD.WebUI.ViewModels.Product;
@model  BaseProductCatalogPageViewModel

<div id="divMenu">
@Html.RouteLink("Home",
                 new
                 {
                     controller = "Home",
                     action = "Index"
                 },
                new { id = "menu0" }
            )
@foreach (Category category in Model.Categories)
{
    
            @Html.RouteLink(category.Name, 
                 new
                  {
                    controller = "Product",
                    action = "GetProductsByCategory",
                    categoryId = category.Id  
                  },
                new
                 {id = "menu" +category.Id.ToString()}
            )
}

</div>

DDD.WebUI/Views/Shared/_ProductCatalogLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-1.7.1.js" type="text/js"></script>
<script src="~/Scripts/jquery.validate.min.js" type="text/js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/js"></script>







<title></title>
</head>

<body>

<div id="header">  
    @RenderSection("TitleContent", required: false)
</div>
<div id="main"></div>
@RenderSection("MenuContent", required: false)
@RenderSection("MainContent", required: false)
@RenderBody()

</body>
</html>

DDD.WebUI/Views/Shared/_ProductDetails.cshtml
@using DDD.WebUI.ViewModels.Product;
@using DDD.Domain.Entities;

@model ProductDetailViewModel



     
<div class="item">

 <table style="width:85%;" id="tblFromProductDetails">
 @if (Model.forCatalog == 0)
 {
      <caption> Catalog View</caption>
 }
 @using (Html.BeginForm("AddToCart", "Cart"))
  {
     
 <tr >
      <td  style="width:400px; text-align:center;"> 
                
         @Html.Partial("ProductTitleImageSet", Model.Product.ProductTitleImages)
                   
      </td>                    

     <td valign="top"> 
       
       <div >
            <div class="showDivAllAboutBrand"><h3><b> @Model.Product.Brand.Name (<span >about brand</span>)</b></h3> 
                       
                 <div class="divAllAboutBrand">
                   <h2><b>@Model.Product.Brand.Name</b></h2>
                        <pre style="white-space: pre-wrap;">@Model.Product.Brand.Description</pre>
                 </div>
            </div>
            <h3>@Model.Product.Name  @Model.Product.Price$</h3>  
            <div id="divProductDescription" > <pre style="white-space: pre-wrap;">@Model.Product.Description </pre></div>
                
            @Html.Partial("ProductQuantityByColor", Model.ProductsQuantityViewModels) 
            @Html.Hidden("productId", Model.Product.Id)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery )
        </div>
      </td></tr>
      <tr><td style="text-align:center;">
      
         <div class="divColorSetDetails" >          
                   @Html.Partial("ProductTitleColors",Model.Product.ProductsQuantity)
        </div>
      
      </td><td>   
        <div  style="vertical-align:bottom;">
            <input type="submit" value="+ Add to cart"  id="btnAddToCart"/>
            <a id="hrefReturnUrl" href="@Model.ReturnUrl"  class="actionButtons" style="margin-left:5px;">Continue shopping</a>
        </div>
         @if (Model.forCatalog == 0)
         {
          <div >         
            @Html.ActionLink("Edit product", "Edit", "ProductAdmin", new { Model.Product.Id, ReturnUrl = @Model.ReturnUrl }, new  {@class="actionButtons"})
            <a href="@Model.ReturnUrl" class="actionButtons" style="margin-left:5px;">Return back to Product List</a>
        </div>
          }

        </td></tr>
    }   
                           
     
 </table>      
</div>


                    
       





<script type="text/javascript">
    $(document).ready(function () {

        var forCatalog = '@Model.forCatalog';
        if (forCatalog == '0') {
            $("#linkProductAdmin").addClass("selected");
        }
        else {

            $("#menu" + "@Model.Product.Category.Id").addClass('selected');
        }

        $('#selectProductColor').live({
            change: function (event) {
                updateSelectOptions('/Product/GetSizesForColor/', 'selectProductColor',
                                'selectProductSize', '@Model.Product.Id', 'Select Size');
                return false;
            }
        });


        $('#selectProductSize').live({
            change: function (event) {
                updateSelectOptionsForQuantity('/Product/GetProductQuantity/', 'selectProductSize',
                                'selectProductQuantity', '@Model.Product.Id',
                                 $("#selectProductColor").val(), 'Select Quantity');
                return false;
            }
        });

        $('#btnAddToCart').live({
            click: function (event) {
                addToCart();
                return false;
            }

        });

        if (forCatalog == '0') {

            $(" #btnAddToCart").remove();
            $("#hrefReturnUrl").remove();
        }



    });
   
     
</script> 



<script type="text/javascript">


    function addToCart() {

        var jsonData = JSON.stringify({
            ProductId: '@Model.Product.Id',
            ProductColorId: $("#selectProductColor").val(),
            ProductSizeId: $("#selectProductSize").val(),
            ProductQuantity: $("#selectProductQuantity").val()
        });
        
        $.ajax({
            url: '@Html.Resolve("/Cart/AddToCartAjax/")',
            type: 'POST',
            dataType: 'json',
            data: jsonData,
            contentType: 'application/json; charset=utf-8',

            error:
                        function (xhr, ajaxOptions, thrownError) {
                            alert(xhr.status + "  " +
                                thrownError);
                        },




            success: function (data) {                
                $("#cartQuantity").html(data.CartQuantity);
                $("#cartTotal").html(data.CartTotal);
            }
        });

    }






    function updateSelectOptions(lookupUrl, parentSelectElementId,
                            childSelectElementId, productId, optionText) {
        $.getJSON(lookupUrl,
            { SearchId: $('#' + parentSelectElementId).val(), ProductId: productId },
            function (data) {
                var html = "<option value='0'>" + optionText + '</option>';
                var len = data.length;
                for (var i = 0; i < len; i++) {
                    html += '<option value="' + data[i].Id + '">' + data[i].Name + '</option>';
                }

                $('#' + childSelectElementId).html(html);
            }
        );

    }




    function updateSelectOptionsForQuantity(lookupUrl, parentSelectElementId,
                            childSelectElementId, productId, colorId, optionText) {
       
        $.getJSON(lookupUrl,
            { SearchId: $('#' + parentSelectElementId).val(), ProductId: productId, ColorId: colorId },
            function (data) {
                var html = "<option value='0'>" + optionText + '</option>';
                var len = parseInt(data.Quantity,10);
                 if (len > 8) len = 8;
               
                
                for (var i = 0; i < len; i++) {
                    var value = (i + 1).toString()
                    html += '<option value="' + value + '">' + value + '</option>';
                }

                $('#' + childSelectElementId).html(html);
            }
        );

    }
</script>

DDD.WebUI/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width" />
<link href="~/Content/User.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-1.7.1.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<title></title>
</head>
<body>
<div>
    
    @RenderBody()
</div>
</body>
</html>