DDD.WebUI/Controllers/CartController.cs
using DDD.Domain.Entities;
using DDD.Domain.Abstract;
using DDD.Domain.Basket;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.Repositories.Abstract;
using DDD.WebUI.ViewModels.Basket;
using DDD.WebUI.ModelBinder;
using DDD.Domain.Shipping;
using DDD.Domain.Order;
using DDD.Repositories.EF;

namespace DDD.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IRepositoryR<ProductTitle, int> repository;
        private IOrderProcessor orderProcessor;



        //--------------------------------------------------
        public CartController(IRepositoryR<ProductTitle, int> repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }
       
        //----------------------------------------------------
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

       //------------------------------------------------------
        public ViewResult Index(Cart cart, string returnUrl)
        {


            return View(new CartIndexViewModel
            {

                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

      
        //----------------------------------------------
        public RedirectToRouteResult AddToCart(Cart cart, string returnUrl,
            int productId , int ProductColorId, int ProductSizeId,  int ProductQuantity)
        {

            ProductTitle product = repository.FindBy(productId);
            if (product != null)
            {

                cart.AddItem(product, ProductColorId,  ProductSizeId,  ProductQuantity);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        
       
        //-------------------------------------------------------------------
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AddToCartAjax(Cart cart,
           int ProductId, int ProductColorId, int ProductSizeId, int ProductQuantity)
        {
          
            ProductTitle product = repository.FindBy(ProductId);
            if (product != null)
            {              
                cart.AddItem(product, ProductColorId, ProductSizeId, ProductQuantity);
            }
            var newdata = new
            {
                CartQuantity = cart.TotalItems(),
                CartTotal = cart.ComputeTotalValue()
            };
            return Json(newdata, JsonRequestBehavior.AllowGet);
        }


        //--------------------------------------------
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            ProductTitle product = repository.FindBy(productId);
            if (product != null)
            {
               
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //---------------------------------------
        public ActionResult Checkout()
        {
            ShippingDetails details = new ShippingDetails();
            details.States = ((ProductTitleRepository)repository).GetProductStates();
            return View(details);
        }



        //-----------------------------------------
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

          
            if (shippingDetails.StateId == 0)
            {
                ModelState.AddModelError("StateId", "Please select a state");
                
            }

            if (ModelState.IsValid)
            {
                //orderProcessor.ProcessOrder(cart, shippingDetails);
                ((ProductTitleRepository)repository).ProcessOrder(cart.Lines);

                cart.Clear();
                return View("Completed");
            }
            else
            {

                    ShippingDetails details = new ShippingDetails();
                    shippingDetails.States = ((ProductTitleRepository)repository).GetProductStates();

                return View(shippingDetails);




            }
        }
    }
}

DDD.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDD.Domain.Abstract;
using DDD.Domain.Entities;
using DDD.Service.Product;
using DDD.Service.Model;
using DDD.WebUI.ViewModels.Product;
using DDD.WebUI.JsonDTOs;
using DDD.Domain.Basket;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;


namespace DDD.WebUI.Controllers
{
    public class ProductController : ProductCatalogBaseController
    {

       private IProductCatalogSevices service;
       

//----------------------------------------------------------------------
        public ProductController(Cart cart, IProductCatalogSevices productService)
            : base( productService)
        {
            this.service = productService;
        }

        //----------------------------------------------------------
        public ActionResult GetProductsByCategory(int categoryId,  Cart cart, int itemsPerPage= 8)
        {
            ProductsByCategoryRequestModel productSearchRequest =
                        GenerateInitialProductSearchRequestFrom(categoryId, itemsPerPage);

            ProductsByCategoryResponseModel response =
                        service.GetProductsByCategory(productSearchRequest);

            ProductSearchResultViewModel productSearchResultView =
                        GetProductSearchResultViewFrom(response);
            productSearchResultView.ItemsPerPage = itemsPerPage;
            productSearchResultView.Cart = cart;

            return View("ProductSearchResult", productSearchResultView);
        }


        // New Search By Category with dafault setting
        //--------------------------------------------------------
        private static ProductsByCategoryRequestModel
                               GenerateInitialProductSearchRequestFrom(int categoryId, int itemsPerPage)
        {
            ProductsByCategoryRequestModel productSearchRequest =
                                     new ProductsByCategoryRequestModel();
            productSearchRequest.NumberOfResultsPerPage = itemsPerPage;
            productSearchRequest.CategoryId = categoryId;
            productSearchRequest.Index = 1;
            productSearchRequest.SortBy = ProductsSortBy.PriceHighToLow;
            return productSearchRequest;
        }
     
        //-----------------------------------------------------------
        private ProductSearchResultViewModel GetProductSearchResultViewFrom(
                                      ProductsByCategoryResponseModel response)
        {
            ProductSearchResultViewModel productSearchResultView =
                                              new ProductSearchResultViewModel();
           productSearchResultView.Categories = base.GetCategories();
           productSearchResultView.Products = response.Products.ToList();
           productSearchResultView.RefinementGroups = response.RefinementGroups;
           productSearchResultView.SelectedCategory = response.SelectedCategory;
           productSearchResultView.SelectedCategoryName = response.SelectedCategoryName;

           productSearchResultView.PagingInfoModel = new PagingInfoModel
           {
               TotalNumberOfPages = response.TotalNumberOfPages,
               NumberOfTitlesFound = response.NumberOfTitlesFound,
               CurrentPage = response.CurrentPage
           }; 

          return productSearchResultView;
        }

        
        public ActionResult GetCategoriesMenu ()
        {

            return PartialView("_Categories", 
                new BaseProductCatalogPageViewModel() {  Categories = base.GetCategories()});
        }

            //----------------------------------------------------
        public JsonResult GetProductQuantity(int SearchId, int ProductId, int ColorId)
        {
            ProductTitle p = service.GetProduct(ProductId);

            var newData = p.ProductsQuantity
                    .Where(c => c.ProductColorId == ColorId && SearchId == c.ProductSizeId)
                    .FirstOrDefault();
            var quantity = 0;
            if (newData != null) quantity = newData.Quantity;

            return Json(new { Quantity = quantity }, JsonRequestBehavior.AllowGet);
        }
        
        //----------------------------------------------------
        public JsonResult GetSizesForColor(int SearchId, int ProductId)
        {
            ProductTitle p = service.GetProduct(ProductId);

            var newData = p.ProductsQuantity
                    .Where( c => c.ProductColorId ==  SearchId)
                    .Select(c => c.ProductSizeId)
                    .Distinct().OrderBy( g => g)
                    .Select( g => new { Id = g, Name = ((ProductSize)g).ToString()});
            return Json(newData, JsonRequestBehavior.AllowGet);
        }
        
        //------------------------------------------------------
       [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult GetProductsByAjax( JsonProductSearchRequest jsonProductSearchRequest)
        {    
           
            ProductsByCategoryRequestModel productSearchRequest =
                          GenerateProductSearchRequestFrom(jsonProductSearchRequest);
            ProductsByCategoryResponseModel response =
                         service.GetProductsByCategory(productSearchRequest);
            ProductSearchResultViewModel productSearchResultView =
                         GetProductSearchResultViewFrom(response);

            var newData = new
            {
                RefinementGroups = productSearchResultView.RefinementGroups,
                SelectedCategory = productSearchResultView.SelectedCategory,
                SelectedCategoryName = productSearchResultView.SelectedCategoryName,
                PagingInfoModel = productSearchResultView.PagingInfoModel,
                Products = productSearchResultView.Products
                   .Select(p => new
                   {
                       Id = p.Id,
                       Name = p.Name,
                       Price = p.Price,

                       ProductColors = p.ProductsQuantity.Select(c => new
                       {
                           ColorName = c.ProductColorValue.ToString(),
                           ColorId = c.ProductColorId.ToString()
                       }).Distinct().ToArray(),      
                      
                       BrandName = p.Brand.Name
                   })
            };

            return Json(newData, JsonRequestBehavior.AllowGet);
        }


        //--------------------------------------------------------------------------
        private static ProductsByCategoryRequestModel GenerateProductSearchRequestFrom(
                                      JsonProductSearchRequest jsonProductSearchRequest)
        {
            ProductsByCategoryRequestModel productSearchRequest =
                                              new ProductsByCategoryRequestModel();

            productSearchRequest.NumberOfResultsPerPage = jsonProductSearchRequest.ItemsPerPage;
            productSearchRequest.Index = jsonProductSearchRequest.Index;
            productSearchRequest.CategoryId = jsonProductSearchRequest.CategoryId;
            productSearchRequest.SortBy = jsonProductSearchRequest.SortBy;


          

            if (jsonProductSearchRequest.RefinementGroups != null)
            {
                foreach (JsonRefinementGroup jsonRefinementGroup in
                                       jsonProductSearchRequest.RefinementGroups)
                {
                    switch ((RefinementGroupings)jsonRefinementGroup.GroupId)
                    {
                        case RefinementGroupings.brand:
                            productSearchRequest.BrandIds =
                                         jsonRefinementGroup.SelectedRefinements;
                            break;
                        case RefinementGroupings.color:
                            productSearchRequest.ColorIds =
                                         jsonRefinementGroup.SelectedRefinements;
                            break;
                        case RefinementGroupings.size:
                            productSearchRequest.SizeIds =
                                         jsonRefinementGroup.SelectedRefinements;
                            break;
                        default:
                            break;
                    }
                }
            }
            return productSearchRequest;
        }

        //---------------------------------------------------------------
        public ActionResult Details(int id, int forCatalog, Cart cart, string ReturnUrl)
        {
           
            ProductDetailViewModel productDetailView = new ProductDetailViewModel();
            
            productDetailView.Product = service.GetProduct(id);            
            productDetailView.Categories = base.GetCategories();
            productDetailView.Cart = cart;
            productDetailView.forCatalog = forCatalog;
            productDetailView.ReturnUrl = ReturnUrl;

            var colors = productDetailView.Product.ProductsQuantity.Where(p => p.Quantity > 0).
                                             Select(p => new { ColorId = p.ProductColorId })
                                             .Distinct();

            IEnumerable<ProductsQuantityViewModel> quantity = colors
                           .Select(p => new ProductsQuantityViewModel()
                           {
                               ColorId = p.ColorId,
                               SizesQuantity = productDetailView.Product.ProductsQuantity
                                                    .Where(s => p.ColorId == s.ProductColorId)
                                                    .OrderBy(s => s.ProductSizeId)
                                                    .Select(s => new SizeQuantityViewModel()
                                                    {

DDD.WebUI/Views/Cart/Checkout.cshtml
@model DDD.Domain.Shipping.ShippingDetails
@{
ViewBag.Title = "SportStore: Checkout";
}


@Scripts.Render("~/Scripts/jquery-1.7.1.js")

@{
    Layout = "~/Views/Shared/_ProductCatalogLayout.cshtml";
}

@section TitleContent {
<div class="title"> 
 CATALOG
</div>         
}

@section MenuContent {
@Html.Action("GetCategoriesMenu", "Product")
   
}

@section MainContent {
<div id="content">
<div id="divCheckout">
<h2>Check out now</h2>
Please enter your details, and we'll ship your goods right away!
@using (Html.BeginForm())
{
 @Html.ValidationSummary()
<h3>Ship to</h3>
<div>@Html.LabelFor(x => x.Name)@Html.EditorFor(x => x.Name)</div>
<h3>Address</h3>
<div> @Html.Label("Line1") @Html.EditorFor(x => x.Line1)</div>
<div> @Html.LabelFor(x => x.Line2)  @Html.EditorFor(x => x.Line2)</div>
<div> @Html.LabelFor(x => x.Line3) @Html.EditorFor(x => x.Line3)</div>
<div> @Html.LabelFor(x => x.City)  @Html.EditorFor(x => x.City)</div>

    

    
 <div>
 @Html.LabelFor(p => Model.StateId)
 @Html.DropDownListForIAttributeSource("StateId", Model.StateId, Model.States, "Select State")
 </div>
    
    
            
<div>@Html.LabelFor(x => x.Zip)  @Html.EditorFor(x => x.Zip)</div>


<h3>Options</h3>
<div >
<label>
@Html.EditorFor(x => x.GiftWrap)
</label>
Gift wrap these items
</div>
<p>
<input class="actionButtons" type="submit" value="Complete order" />
</p>

}
</div>
</div>
}

DDD.WebUI/Views/Cart/Completed.cshtml
@{
ViewBag.Title = "SportStore: Checkout";
}

@{
    Layout = "~/Views/Shared/_ProductCatalogLayout.cshtml";
}

@section TitleContent {
<div class="title"> 
 CATALOG 
</div>         
}



@section MenuContent {
       @Html.Action("GetCategoriesMenu", "Product")  
}

@section MainContent {
<div id="content">
<div id="#divCompleted">
<h2>Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible.
</div>
</div>
}

DDD.WebUI/Views/Cart/Index.cshtml
@using DDD.Domain.Entities;
@using DDD.WebUI.ViewModels.Basket;
@model CartIndexViewModel

@Scripts.Render("~/Scripts/jquery-1.7.1.js")

@{
    Layout = "~/Views/Shared/_ProductCatalogLayout.cshtml";
}

@section TitleContent {
<div class="title"> 
CATALOG
</div>         
}



@section MenuContent {
@Html.Action("GetCategoriesMenu", "Product")
}


@{
    var col = Model.Cart.Lines.Sum(p => p.Quantity);
}

<table id="tblCart" align="center">
<caption>You Have (@col) Items in Your Shopping Bag</caption>
<thead>

<tr >

<th align="left" colspan="2" >Your Items</th>

<th align="center" >Item Price</th>
<th align="center" >Quantity</th>
<th align="center" >Subtotal</th>
<th align="center">Remove</th>
</tr>
</thead>
<tbody>

@foreach (var line in Model.Cart.Lines)
{
<tr>
<td align="left" valign="top"  >


      <img src="@Url.Action("GetImage", "Product", new { id = line.Id }, null)"
       width="70px;" alt="img-@line.Id"/>
</td>


<td align="left" valign="top">
<a href="/Product/Details/@line.Id"> @line.BrandName  @line.Name</a><br />
           Size @line.ProductSizeName, Color @line.ProductColorName   </td>

<td align="center" valign="top">@line.Price.ToString("c")</td>

<td align="center" valign="top"  >@line.Quantity<br /></td>

<td  valign="top" align="center">@((line.Quantity * line.Price).ToString("c")) </td>


<td valign="top" align="center">


            @using (Html.BeginForm("RemoveFromCart", "Cart"))
            {
               <span class="DeleteLink" >
                <img alt="Delete Item " src="http://pics.ebaystatic.com/aw/pics/icon/iconTrashcan_16x16.gif" 
                onmouseover="this.src='../../Content/Images/iconTrashcanSelected_16x16.gif'"
                onmouseout="this.src='http://pics.ebaystatic.com/aw/pics/icon/iconTrashcan_16x16.gif'" border="0"/>
               </span>
                 @Html.Hidden("productId", line.Id)
                 @Html.HiddenFor(x => x.ReturnUrl)
            }
</td>        


</tr>
}
</tbody>
<tfoot>
<tr>
<td colspan="4" align="right">Total:</td>
<td align="center">
 @Model.Cart.ComputeTotalValue().ToString("c")
</td><td></td>
</tr>
</tfoot>
</table>

<p align="center" class="actionButtons">
<a href="@Model.ReturnUrl">Continue shopping</a>

@if (col > 0){
     @Html.ActionLink("Checkout now", "CheckOut")
}
</p>


<script type="text/javascript">
    $(document).ready(function () {

$('.DeleteLink').click(function() { 
    $(this).closest('form')[0].submit();
});




})

</script>